"""
Builder for train_unet_ham10k_colab.ipynb
Generates a structured, zero-leakage U-Net training notebook for Google Colab.
Updated with safe encoding reader for CSVs.
"""

import json
from pathlib import Path

def create_notebook():
    cells = []

    # Cell 0: Header & Konsep Riset
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🩺 Pelatihan Model Segmentasi U-Net Lesi Kulit (Google Colab)\n",
            "\n",
            "**Tujuan:** Melatih model segmentasi U-Net menggunakan masker lesi HAM10000 (Tschandl et al., Nature Medicine 2020) dengan protokol **Zero Data Leakage**.\n",
            "* **Strategi Anti-Bocor:** U-Net hanya dilatih dari partisi `train` dan divalidasi pada partisi `val`. Partisi `test` 100% diisolasi.\n",
            "* **Arsitektur:** U-Net dengan Encoder ResNet-34 (Pre-trained ImageNet) & kombinasi fungsi loss medis $\\mathcal{L} = \\text{BCE} + (1 - \\text{Dice})$.\n",
            "* **Penyimpanan:** Bobot model terbaik (`best_unet_ham10k.pth`), kurva metrik, dan sampel prediksi disimpan langsung ke Google Drive."
        ]
    })

    # Cell 1: Mount Google Drive
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 1. Hubungkan ke Google Drive\n",
            "import os\n",
            "from pathlib import Path\n",
            "from google.colab import drive\n",
            "\n",
            "drive.mount('/content/drive')\n",
            "\n",
            "# Folder penyimpanan hasil di Google Drive\n",
            "OUTPUT_DIR = Path('/content/drive/MyDrive/riset_kulit_segmentasi')\n",
            "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "print(f\"Folder output Google Drive siap: {OUTPUT_DIR}\")"
        ]
    })

    # Cell 2: Instalasi Dependensi & Deteksi GPU
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 2. Instalasi library dan verifikasi GPU\n",
            "!pip install -q segmentation-models-pytorch albumentations kagglehub\n",
            "\n",
            "import torch\n",
            "\n",
            "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "print(f\"Device aktif: {device}\")\n",
            "if torch.cuda.is_available():\n",
            "    print(f\"GPU Name: {torch.cuda.get_device_name(0)}\")\n",
            "    print(f\"VRAM: {torch.cuda.get_device_properties(0).total_memory / (1024**3):.2f} GB\")"
        ]
    })

    # Cell 3: Unduh Dataset Kaggle via KaggleHub
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 3. Pemuatan dataset dari Kaggle (Otomatis via KaggleHub)\n",
            "import kagglehub\n",
            "\n",
            "print(\"Mengunduh dataset citra HAM10000...\")\n",
            "path_images = kagglehub.dataset_download(\"nadiraanindita/dataset-riset-ham10k\")\n",
            "\n",
            "print(\"Mengunduh dataset masker HAM10000...\")\n",
            "path_masks = kagglehub.dataset_download(\"nadiraanindita/ham-segmentations-lesion-riset-saya\")\n",
            "\n",
            "print(\"Mengunduh metadata partisi (split train/val/test)...\")\n",
            "path_split = kagglehub.dataset_download(\"nadiraanindita/ham10k-and-isic-2019\")\n",
            "\n",
            "DIR_IMAGES = Path(path_images)\n",
            "DIR_MASKS = Path(path_masks)\n",
            "DIR_SPLIT = Path(path_split)\n",
            "\n",
            "print(f\"Direktori Images: {DIR_IMAGES}\")\n",
            "print(f\"Direktori Masks : {DIR_MASKS}\")\n",
            "print(f\"Direktori Split : {DIR_SPLIT}\")"
        ]
    })

    # Cell 4: Audit & Matching Image ID <-> Mask ID (Zero-Leakage Filtering + Safe Encoding)
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 4. Audit & Matching Image ID <-> Mask ID (Zero Data Leakage Protocol)\n",
            "import re\n",
            "import pandas as pd\n",
            "\n",
            "# Helper fungsi pembaca CSV aman multi-encoding\n",
            "def safe_read_csv(fpath):\n",
            "    for enc in ['utf-8', 'latin-1', 'cp1252', 'iso-8859-1']:\n",
            "        try:\n",
            "            return pd.read_csv(fpath, encoding=enc)\n",
            "        except UnicodeDecodeError:\n",
            "            continue\n",
            "    return pd.read_csv(fpath, encoding_errors='replace')\n",
            "\n",
            "# Temukan file CSV split di direktori split\n",
            "csv_files = list(DIR_SPLIT.glob('**/*.csv'))\n",
            "print(f\"File CSV ditemukan: {[f.name for f in csv_files]}\")\n",
            "\n",
            "# Prioritas 1: Gunakan split_assignments.csv jika tersedia\n",
            "split_file = None\n",
            "for f in csv_files:\n",
            "    if f.name == 'split_assignments.csv':\n",
            "        split_file = f\n",
            "        break\n",
            "\n",
            "if split_file:\n",
            "    df_meta = safe_read_csv(split_file)\n",
            "    print(f\"Menggunakan file master split: {split_file.name} ({len(df_meta):,} baris)\")\n",
            "else:\n",
            "    # Prioritas 2: Muat train.csv, val.csv, test.csv\n",
            "    dfs = []\n",
            "    for f in csv_files:\n",
            "        if f.name in ['train.csv', 'val.csv', 'test.csv']:\n",
            "            df_temp = safe_read_csv(f)\n",
            "            if 'split' not in df_temp.columns:\n",
            "                df_temp['split'] = f.stem\n",
            "            dfs.append(df_temp)\n",
            "    if dfs:\n",
            "        df_meta = pd.concat(dfs, ignore_index=True)\n",
            "    else:\n",
            "        df_meta = pd.concat([safe_read_csv(f) for f in csv_files], ignore_index=True)\n",
            "\n",
            "# Standarisasi nama kolom image_id\n",
            "for col in ['image', 'isic_id', 'Image', 'IMAGE']:\n",
            "    if col in df_meta.columns and 'image_id' not in df_meta.columns:\n",
            "        df_meta = df_meta.rename(columns={col: 'image_id'})\n",
            "\n",
            "df_meta = df_meta.drop_duplicates(subset=['image_id'])\n",
            "print(f\"Total metadata citra termuat: {len(df_meta):,} baris unik\")\n",
            "\n",
            "# Indeks seluruh path file fisik citra (.jpg)\n",
            "all_images = {}\n",
            "for p in DIR_IMAGES.glob('**/*.jpg'):\n",
            "    all_images[p.stem] = str(p)\n",
            "\n",
            "# Indeks seluruh path file fisik masker (.png)\n",
            "all_masks = {}\n",
            "for p in DIR_MASKS.glob('**/*.png'):\n",
            "    clean_id = re.sub(r'_segmentation$', '', p.stem)\n",
            "    all_masks[clean_id] = str(p)\n",
            "\n",
            "print(f\"Total citra fisik ditemukan : {len(all_images):,}\")\n",
            "print(f\"Total masker fisik ditemukan: {len(all_masks):,}\")\n",
            "\n",
            "# Filter hanya baris yang memiliki pasangan citra & masker lengkap\n",
            "matched_records = []\n",
            "for _, row in df_meta.iterrows():\n",
            "    img_id = str(row['image_id']).strip()\n",
            "    split_val = str(row.get('split', '')).strip().lower()\n",
            "    \n",
            "    if img_id in all_images and img_id in all_masks:\n",
            "        matched_records.append({\n",
            "            'image_id': img_id,\n",
            "            'image_path': all_images[img_id],\n",
            "            'mask_path': all_masks[img_id],\n",
            "            'split': split_val\n",
            "        })\n",
            "\n",
            "df_matched = pd.DataFrame(matched_records)\n",
            "print(f\"Total citra berpasangan masker: {len(df_matched):,}\")\n",
            "\n",
            "# Filter ketat: HANYA train dan val yang masuk ke U-Net (Test 100% diisolasi)\n",
            "train_df = df_matched[df_matched['split'] == 'train'].reset_index(drop=True)\n",
            "val_df = df_matched[df_matched['split'] == 'val'].reset_index(drop=True)\n",
            "test_df = df_matched[df_matched['split'] == 'test'].reset_index(drop=True)\n",
            "\n",
            "print(\"\\n=== HASIL PARTISI ZERO-LEAKAGE U-NET ===\")\n",
            "print(f\"Train Set (Dipakai U-Net Latih)   : {len(train_df):,} citra\")\n",
            "print(f\"Val Set   (Dipakai U-Net Evaluasi): {len(val_df):,} citra\")\n",
            "print(f\"Test Set  (DIISOLASI TOTAL)       : {len(test_df):,} citra (0% bocor)\")\n",
            "\n",
            "assert len(train_df) > 0, \"Data train kosong! Periksa format kolom 'split' di CSV.\"\n",
            "assert len(val_df) > 0, \"Data val kosong! Periksa format kolom 'split' di CSV.\""
        ]
    })

    # Cell 5: Dataset PyTorch & Augmentasi Albumentations
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 5. PyTorch Dataset & Pipeline Augmentasi\n",
            "import cv2\n",
            "import numpy as np\n",
            "import albumentations as A\n",
            "from albumentations.pytorch import ToTensorV2\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "\n",
            "IMG_SIZE = 256\n",
            "BATCH_SIZE = 32\n",
            "NUM_WORKERS = 2\n",
            "\n",
            "train_transforms = A.Compose([\n",
            "    A.Resize(IMG_SIZE, IMG_SIZE),\n",
            "    A.HorizontalFlip(p=0.5),\n",
            "    A.VerticalFlip(p=0.5),\n",
            "    A.RandomRotate90(p=0.5),\n",
            "    A.ShiftScaleRotate(shift_limit=0.06, scale_limit=0.1, rotate_limit=15, p=0.5),\n",
            "    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),\n",
            "    ToTensorV2()\n",
            "])\n",
            "\n",
            "val_transforms = A.Compose([\n",
            "    A.Resize(IMG_SIZE, IMG_SIZE),\n",
            "    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),\n",
            "    ToTensorV2()\n",
            "])\n",
            "\n",
            "class SkinLesionDataset(Dataset):\n",
            "    def __init__(self, df, transform=None):\n",
            "        self.df = df\n",
            "        self.transform = transform\n",
            "\n",
            "    def __len__(self):\n",
            "        return len(self.df)\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        row = self.df.iloc[idx]\n",
            "        img = cv2.imread(row['image_path'])\n",
            "        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
            "        \n",
            "        mask = cv2.imread(row['mask_path'], cv2.IMREAD_GRAYSCALE)\n",
            "        mask = (mask > 127).astype(np.float32)  # Biner [0.0, 1.0]\n",
            "\n",
            "        if self.transform:\n",
            "            augmented = self.transform(image=img, mask=mask)\n",
            "            img = augmented['image']\n",
            "            mask = augmented['mask'].unsqueeze(0)\n",
            "\n",
            "        return img, mask, row['image_id']\n",
            "\n",
            "train_ds = SkinLesionDataset(train_df, transform=train_transforms)\n",
            "val_ds = SkinLesionDataset(val_df, transform=val_transforms)\n",
            "\n",
            "train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)\n",
            "val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)\n",
            "\n",
            "print(f\"DataLoader siap: {len(train_loader)} batch latih, {len(val_loader)} batch validasi.\")"
        ]
    })

    # Cell 6: Visualisasi Sanity Check Batch Latih
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 6. Sanity check: Visualisasi sampel citra & masker ground truth\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "sample_imgs, sample_masks, sample_ids = next(iter(train_loader))\n",
            "mean = np.array([0.485, 0.456, 0.406])\n",
            "std = np.array([0.229, 0.224, 0.225])\n",
            "\n",
            "fig, axes = plt.subplots(2, 4, figsize=(16, 8))\n",
            "for i in range(4):\n",
            "    img_np = sample_imgs[i].permute(1, 2, 0).cpu().numpy()\n",
            "    img_np = np.clip(img_np * std + mean, 0, 1)\n",
            "    mask_np = sample_masks[i, 0].cpu().numpy()\n",
            "    \n",
            "    axes[0, i].imshow(img_np)\n",
            "    axes[0, i].set_title(f\"{sample_ids[i]}\\n(Citra Asli)\")\n",
            "    axes[0, i].axis('off')\n",
            "    \n",
            "    axes[1, i].imshow(mask_np, cmap='gray')\n",
            "    axes[1, i].set_title(\"Masker Ground Truth\")\n",
            "    axes[1, i].axis('off')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    })

    # Cell 7: Arsitektur U-Net & Kombinasi Loss Medis (BCE + Dice)
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 7. Arsitektur U-Net ResNet-34 & Loss Medis (BCE + Dice)\n",
            "import torch.nn as nn\n",
            "import segmentation_models_pytorch as smp\n",
            "\n",
            "# Inisialisasi U-Net dengan backbone ResNet-34 pre-trained\n",
            "model = smp.Unet(\n",
            "    encoder_name=\"resnet34\",\n",
            "    encoder_weights=\"imagenet\",\n",
            "    in_channels=3,\n",
            "    classes=1,\n",
            "    activation=None\n",
            ").to(device)\n",
            "\n",
            "class BCEDiceLoss(nn.Module):\n",
            "    def __init__(self, smooth=1e-5):\n",
            "        super().__init__()\n",
            "        self.bce = nn.BCEWithLogitsLoss()\n",
            "        self.smooth = smooth\n",
            "\n",
            "    def forward(self, pred_logits, targets):\n",
            "        bce_loss = self.bce(pred_logits, targets)\n",
            "        probs = torch.sigmoid(pred_logits)\n",
            "        \n",
            "        probs_flat = probs.view(-1)\n",
            "        targets_flat = targets.view(-1)\n",
            "        \n",
            "        intersection = (probs_flat * targets_flat).sum()\n",
            "        dice_score = (2. * intersection + self.smooth) / (probs_flat.sum() + targets_flat.sum() + self.smooth)\n",
            "        dice_loss = 1.0 - dice_score\n",
            "        \n",
            "        return bce_loss + dice_loss\n",
            "\n",
            "criterion = BCEDiceLoss()\n",
            "optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)\n",
            "scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=2)\n",
            "print(\"Model U-Net ResNet-34 & Loss Medis berhasil dikonfigurasi.\")"
        ]
    })

    # Cell 8: Training & Validation Loop dengan Automatic Mixed Precision (AMP)
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 8. Pelatihan U-Net dengan Automatic Mixed Precision (AMP)\n",
            "import time\n",
            "from torch.cuda.amp import GradScaler, autocast\n",
            "\n",
            "EPOCHS = 15\n",
            "scaler = GradScaler()\n",
            "best_val_dice = 0.0\n",
            "history = []\n",
            "\n",
            "checkpoint_path = OUTPUT_DIR / 'best_unet_ham10k.pth'\n",
            "print(f\"Memulai pelatihan {EPOCHS} epoch. Checkpoint akan disimpan di: {checkpoint_path}\")\n",
            "\n",
            "for epoch in range(1, EPOCHS + 1):\n",
            "    start_time = time.time()\n",
            "    \n",
            "    # --- Training Phase ---\n",
            "    model.train()\n",
            "    train_loss = 0.0\n",
            "    train_dice = 0.0\n",
            "    \n",
            "    for imgs, masks, _ in train_loader:\n",
            "        imgs, masks = imgs.to(device), masks.to(device)\n",
            "        optimizer.zero_grad()\n",
            "        \n",
            "        with autocast():\n",
            "            outputs = model(imgs)\n",
            "            loss = criterion(outputs, masks)\n",
            "            \n",
            "        scaler.scale(loss).backward()\n",
            "        scaler.step(optimizer)\n",
            "        scaler.update()\n",
            "        \n",
            "        train_loss += loss.item() * imgs.size(0)\n",
            "        preds = (torch.sigmoid(outputs) > 0.5).float()\n",
            "        inter = (preds * masks).sum().item()\n",
            "        train_dice += ((2.0 * inter) / (preds.sum().item() + masks.sum().item() + 1e-5)) * imgs.size(0)\n",
            "        \n",
            "    train_loss /= len(train_ds)\n",
            "    train_dice /= len(train_ds)\n",
            "    \n",
            "    # --- Validation Phase ---\n",
            "    model.eval()\n",
            "    val_loss = 0.0\n",
            "    val_dice = 0.0\n",
            "    val_iou = 0.0\n",
            "    \n",
            "    with torch.no_grad():\n",
            "        for imgs, masks, _ in val_loader:\n",
            "            imgs, masks = imgs.to(device), masks.to(device)\n",
            "            \n",
            "            with autocast():\n",
            "                outputs = model(imgs)\n",
            "                loss = criterion(outputs, masks)\n",
            "                \n",
            "            val_loss += loss.item() * imgs.size(0)\n",
            "            preds = (torch.sigmoid(outputs) > 0.5).float()\n",
            "            inter = (preds * masks).sum().item()\n",
            "            union = (preds + masks).clamp(0, 1).sum().item()\n",
            "            \n",
            "            val_dice += ((2.0 * inter) / (preds.sum().item() + masks.sum().item() + 1e-5)) * imgs.size(0)\n",
            "            val_iou += ((inter + 1e-5) / (union + 1e-5)) * imgs.size(0)\n",
            "            \n",
            "    val_loss /= len(val_ds)\n",
            "    val_dice /= len(val_ds)\n",
            "    val_iou /= len(val_ds)\n",
            "    elapsed = time.time() - start_time\n",
            "    \n",
            "    scheduler.step(val_dice)\n",
            "    history.append({\n",
            "        'epoch': epoch,\n",
            "        'train_loss': train_loss,\n",
            "        'train_dice': train_dice,\n",
            "        'val_loss': val_loss,\n",
            "        'val_dice': val_dice,\n",
            "        'val_iou': val_iou,\n",
            "        'time_sec': elapsed\n",
            "    })\n",
            "    \n",
            "    is_best = val_dice > best_val_dice\n",
            "    if is_best:\n",
            "        best_val_dice = val_dice\n",
            "        torch.save(model.state_dict(), checkpoint_path)\n",
            "        saved_flag = \"[SIMPAN KE GOOGLE DRIVE]\"\n",
            "    else:\n",
            "        saved_flag = \"\"\n",
            "        \n",
            "    print(f\"Epoch {epoch:02d}/{EPOCHS:02d} [{elapsed:.1f}s] - Train Loss: {train_loss:.4f} | Train Dice: {train_dice:.4f} | Val Loss: {val_loss:.4f} | Val Dice: {val_dice:.4f} | Val IoU: {val_iou:.4f} {saved_flag}\")\n",
            "\n",
            "print(f\"\\nPelatihan tuntas! Model terbaik tersimpan dengan Val Dice: {best_val_dice:.4f}\")"
        ]
    })

    # Cell 9: Plot Kurva Evaluasi & Ekspor Riwayat ke Drive
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 9. Visualisasi kurva pelatihan & penyimpanan CSV ke Google Drive\n",
            "df_history = pd.DataFrame(history)\n",
            "csv_history_path = OUTPUT_DIR / 'unet_training_history.csv'\n",
            "df_history.to_csv(csv_history_path, index=False)\n",
            "print(f\"Log riwayat tersimpan di: {csv_history_path}\")\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "# Plot Loss\n",
            "axes[0].plot(df_history['epoch'], df_history['train_loss'], 'b-o', label='Train Loss')\n",
            "axes[0].plot(df_history['epoch'], df_history['val_loss'], 'r-s', label='Val Loss')\n",
            "axes[0].set_title('Kurva Loss (BCE + Dice)')\n",
            "axes[0].set_xlabel('Epoch')\n",
            "axes[0].set_ylabel('Loss')\n",
            "axes[0].grid(True, linestyle='--', alpha=0.6)\n",
            "axes[0].legend()\n",
            "\n",
            "# Plot Dice Score\n",
            "axes[1].plot(df_history['epoch'], df_history['train_dice'], 'b-o', label='Train Dice')\n",
            "axes[1].plot(df_history['epoch'], df_history['val_dice'], 'g-s', label='Val Dice')\n",
            "axes[1].set_title('Kurva Dice Score (F1 Overlap)')\n",
            "axes[1].set_xlabel('Epoch')\n",
            "axes[1].set_ylabel('Dice Score')\n",
            "axes[1].grid(True, linestyle='--', alpha=0.6)\n",
            "axes[1].legend()\n",
            "\n",
            "plot_path = OUTPUT_DIR / 'unet_training_curves.png'\n",
            "plt.tight_layout()\n",
            "plt.savefig(plot_path, dpi=300)\n",
            "plt.show()\n",
            "print(f\"Grafik kurva tersimpan di: {plot_path}\")"
        ]
    })

    # Cell 10: Uji Visualisasi Prediksi Masker U-Net pada Validasi
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 10. Visualisasi komparasi masker: Citra Asli vs Ground Truth vs Prediksi U-Net\n",
            "model.load_state_dict(torch.load(checkpoint_path, map_location=device))\n",
            "model.eval()\n",
            "\n",
            "val_imgs, val_masks, val_ids = next(iter(val_loader))\n",
            "val_imgs = val_imgs.to(device)\n",
            "\n",
            "with torch.no_grad():\n",
            "    with autocast():\n",
            "        preds = model(val_imgs)\n",
            "        preds = (torch.sigmoid(preds) > 0.5).float().cpu().numpy()\n",
            "\n",
            "fig, axes = plt.subplots(4, 3, figsize=(12, 16))\n",
            "\n",
            "for i in range(4):\n",
            "    img_np = val_imgs[i].permute(1, 2, 0).cpu().numpy()\n",
            "    img_np = np.clip(img_np * std + mean, 0, 1)\n",
            "    gt_np = val_masks[i, 0].cpu().numpy()\n",
            "    pred_np = preds[i, 0]\n",
            "    \n",
            "    axes[i, 0].imshow(img_np)\n",
            "    axes[i, 0].set_title(f\"{val_ids[i]}\\n(Citra Asli)\")\n",
            "    axes[i, 0].axis('off')\n",
            "    \n",
            "    axes[i, 1].imshow(gt_np, cmap='gray')\n",
            "    axes[i, 1].set_title(\"Ground Truth Dokter\")\n",
            "    axes[i, 1].axis('off')\n",
            "    \n",
            "    axes[i, 2].imshow(pred_np, cmap='gray')\n",
            "    axes[i, 2].set_title(\"Prediksi U-Net (Hasil Latih)\")\n",
            "    axes[i, 2].axis('off')\n",
            "\n",
            "pred_plot_path = OUTPUT_DIR / 'unet_sample_predictions.png'\n",
            "plt.tight_layout()\n",
            "plt.savefig(pred_plot_path, dpi=300)\n",
            "plt.show()\n",
            "print(f\"Sampel visualisasi tersimpan di: {pred_plot_path}\")"
        ]
    })

    nb = {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {
                "gpuType": "T4",
                "provenance": []
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    target_path = Path("kode/5_segmentasi_unet/train_unet_ham10k_colab.ipynb")
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2, ensure_ascii=False)
    print(f"Notebook berhasil diperbarui: {target_path} ({len(cells)} cells)")

if __name__ == "__main__":
    create_notebook()
